{% set name = "yacs" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yacs-{{ version }}.tar.gz
  sha256: efc4c732942b3103bea904ee89af98bcd27d01f0ac12d8d4d369f1e7a2914384

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml

test:
  imports:
    - yacs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rbgirshick/yacs
  summary: Yet Another Configuration System
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - Tonylac77
