package:
  name: psovina
  version: 1.0

source:
  - url: https://sourceforge.net/projects/psovina/files/binaries/psovina-1.0/Ubuntu-11.04_x86_64_psovina/download
    sha256: e9d55f27c2a087d4e0cd635e78811dbc851f41336b67a33210b79c0695722c75
    fn: psovina1
  - url: https://sourceforge.net/projects/psovina/files/binaries/psovina-1.1/Ubuntu_x86_64_psovina/download
    sha256: c52b0a5097a787abfffaa8376b845ca137dadd2019cd4aac3553160d3ec0ed40
    fn: psovina1.1
  - url: https://sourceforge.net/projects/psovina/files/binaries/psovina-2.0/Ubuntu-15.04_psovina2/download
    sha256: cdbaa67480c4341c7100c13cec46b1ad6c34441a09601c1938c2906a53420938
    fn: psovina2


build:
  number: 0
  skip: true  # [not linux]

test:
  commands:
    - psovina1 --help
    - psovina1.1 --help
    - psovina2 --help

about:
  home: https://sourceforge.net/projects/psovina/
  license: MIT
  license_file: LICENSE.txt
  summary: A fast docking tool based on the efficient optimization algorithm of Particle Swarm Intelligence and the framework of AutoDock Vina.
  description: A fast docking tool based on the efficient optimization algorithm of Particle Swarm Intelligence and the framework of AutoDock Vina.
  doc_url: https://sourceforge.net/projects/psovina/
  dev_url: https://sourceforge.net/projects/psovina/
  citation: Ng MC, Fong S, Siu SW. PSOVina The hybrid particle swarm optimization algorithm for protein-ligand docking. J Bioinform Comput Biol. 2015 Jun;13(3):1541007. doi 10.1142/S0219720015410073. Epub 2015 Feb 10. PMID 25800162.
  citation_file: CITATION.md
  
extra:
  recipe-maintainers:
    - Tonylac77