{% set name = "espsim" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/espsim-{{ version }}.tar.gz
  sha256: 0b4438b4a3c8fe57c69dff9cb5e6e4044e9d376078133a79a01c1bbb3d689443

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - espsim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hesther/espsim
  summary: Scoring of shape and ESP similarity with RDKit
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tonylac77
