package:
  name: gnina
  version: 1.1

source:
  url: https://github.com/gnina/gnina/releases/download/v1.1/gnina
  sha256: cd5f12d88f63bef2f637ef183beb24f1620ba97944d88173b76fbd373e46d84f
  fn: gnina

build:
  number: 0
  skip: true  # [not linux]

test:
  commands:
    - gnina --help

about:
  home: https://github.com/gnina/gnina
  license: None
  summary: gnina (pronounced NEE-na) is a molecular docking program with integrated support for scoring and optimizing ligands using convolutional neural networks. It is a fork of smina, which is a fork of AutoDock Vina.
  description: gnina (pronounced NEE-na) is a molecular docking program with integrated support for scoring and optimizing ligands using convolutional neural networks. It is a fork of smina, which is a fork of AutoDock Vina.
  doc_url: https://github.com/gnina/gnina
  dev_url: https://github.com/gnina/gnina
  
extra:
  recipe-maintainers:
    - Tonylac77
